export const directoryActionTypes = {
    FETCH_SECTIONS_START: 'FETCH_SECTIONS_START',
    FETCH_SECTIONS_SUCCESS: 'FETCH_SECTIONS_SUCCESS',
    FETCH_SECTIONS_FAILURE: 'FETCH_SECTIONS_FAILURE',
    FETCH_SECTION_ITEMS_START: 'FETCH_SECTION_ITEMS_START',
    FETCH_SECTION_ITEMS_SUCCESS: 'FETCH_SECTION_ITEMS_SUCCESS',
    FETCH_SECTION_ITEMS_FAILURE: 'FETCH_SECTION_ITEMS_FAILURE'
}