export const adminActionTypes = {
    DEVICE_BAR_TOGGLE: 'DEVICE_BAR_TOGGLE',
    SHOW_DEVICE_ITEMS_MODAL: 'SHOW_DEVICE_ITEMS_MODAL',
    SHOW_ADD_DEVICE_MODAL: 'SHOW_ADD_DEVICE_MODAL',
    SHOW_DEVICE_EDIT_MODAL: 'SHOW_DEVICE_EDIT_MODAL',
    SHOW_ADD_DEVICE_ITEM_MODAL: 'SHOW_ADD_DEVICE_ITEM_MODAL',
    SHOW_EDIT_DEVICE_ITEM_MODAL: 'SHOW_EDIT_DEVICE_ITEM_MODAL',
    GET_DEVICE_ITEM_ID: 'GET_DEVICE_ITEM_ID',
    GET_DEVICE_TITLE: 'GET_DEVICE_TITLE',
    GET_DEVICE_DATA: 'GET_DEVICE_DATA'
}